<div class="footer-buttom-categories">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-buttom-categories')
        ->toHtml();
    ?>    
</div>

<div class="footer-buttom-log-burning">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-buttom-log-burning')
        ->toHtml();
    ?>
</div>

<div class="footer-buttom-policies">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-buttom-policies')
        ->toHtml();
    ?>
</div>
