<div class="footer-top-banner-img">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-top-banner-img')
        ->toHtml();
    ?>
</div>
<div class="footer-top-banner-title">
<?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-top-banner-title')
        ->toHtml();
    ?>
</div>