<div class="footer-middle-shipping">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-shipping')
        ->toHtml();
    ?>
</div>
<div class="footer-middle-find">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-find')
        ->toHtml();
    ?>
</div>
<div class="footer-middle-money">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-money')
        ->toHtml();
    ?>
</div>
<div class="footer-middle-contact-us">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-contact-us')
        ->toHtml();
    ?>
</div>