<div class="footer-top-left">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-top-left')
        ->toHtml();
    ?>
</div>

<div class="footer-top-middle">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-top-middle')
        ->toHtml();
    ?>
</div>

<div class="footer-top-right">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-top-right')
        ->toHtml();
    ?>
</div>